CREATE TABLE IF NOT EXISTS emoji_mood (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    emoji VARCHAR(255) NOT NULL,
    mood_description VARCHAR(255),
    genre_hint VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);